### ISSUE TITLE
CIF read generates error

### ISSUE THREAD

**Issue by dch0ph** [CCP-NC/magresview-2#12]
[CONGRS_geomopt-out.zip](https://github.com/CCP-NC/magresview-2/files/10677110/CONGRS_geomopt-out.zip)

The attached CIF (zipped to allow GutHib to accept) fails to load with the error:

![image](https://user-images.githubusercontent.com/20069699/217298125-ea6929c1-30b8-46e8-9d01-4b21956b92f9.png)

OK, reading CIFs is not a top priority for MagresView, but it does suggest some fragility in the underlying crystal viewer.

MV1 reads the file, but makes a mess of "loading as molecule".

**Comment by jkshenton** [comment]
Thanks @dch0ph.

It seems to be a problem with the library used to parse CIF files: https://github.com/stur86/crystcif-parse rather than MV2 or crystvis-js. 

Your attached CIF file doesn't contain `_atom_site_type_symbol` tags (i.e. the element symbol), only the labels. Adding these in manually makes everything work nicely (including the 'load as molecule') in MV2. 

I'm guessing that other parsers/visualisers fall back on extracting the element from the labels. We could use regex to split the labels at the first non-alpha character and assume the first bit is the element symbol.

**Comment by dch0ph** [comment]
Good spot! 

MV2/crystvis-js could perhaps handle this better, but as you say the main problem is the CIF parsing:

From the official documentation:

![image](https://user-images.githubusercontent.com/20069699/217310506-0c5b6425-be39-4c5e-8f97-539633c422f7.png)

crystcif-parse is in the wrong, since the CIF is valid. The documentation also implies ("component 0") that the `_atom_site_type_symbol` must be extractable from the `_atom_site_label` in this case.

CIF is a horridly complicated format, and I do worry about the wisdom / maintainability of both a CIF parser and crystal viewer...
